import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const josefin_Sans = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "loopstudios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefin_Sans.className} antialiased `}>
        <div>
          <Navbar />
        </div>
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
