import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const josefin_Sans = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefin_Sans.className} antialiased relative`}>
        <Navbar />
        <main className="md:max-w-2xl xl:max-w-7xl max-w-none mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
